/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.scala-application-conventions")
    application
    scala
    antlr
}



application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.scala-lang:scala3-library_3:3.5.2")
    antlr("org.antlr:antlr4:4.13.2")
}
// antlr4 Grammar.g4     dans cst et puis quand il a généré les fichiers, javac -cp antlr-4.13.2-complete.jar *.java      dans cst.